feat : 게임 시작 화면 구성
KEEPER31337/Game-Baseball pull request #27
Opened 2023-06-04 07:07 UTC by KimHaejoong1

- 게임 시작 화면 구성입니다
- 포인트 입력 없거나 조건에 맞지 않으면 스타트 비활성화해두었습니다
- #1

## 연관 이슈

- #1 

## 작업 요약

- 시작 페이지입니다

## 작업 상세 설명

- 포인트 입력 없거나 조건에 맞지 않으면 스타트 비활성화해두었습니다
- props로 onStart 함수를 받아서 스타트 버튼 누르면 게임 화면으로 넘어가게했습니다

## 리뷰 요구사항

- App.tsx 파일을 바꿨는데 괜찮은지 확인 부탁드립니다
- 만들다보니 알림창보다 hover로 가는게 훨씬 보기 좋은 것 같아서 이렇게 구현했는데 혹시 다른 의견 있으시면 제안 부탁드립니다
- 리뷰 예상 시간 : 5분

- Preview 이미지
![image](https://github.com/KEEPER31337/Game-Baseball/assets/128127416/4846a350-0b10-4c86-b688-03138a83f54d)

2023-06-04 07:09 UTC, jasper200207 approved these changes
수고하셨습니다.

2023-06-04 07:09 UTC, jasper200207 commented on src/screens/GameStart.tsx
> +        className="text-2xl enabled:hover:text-pointBlue"
hover 좋은거 같습니다!

2023-06-23 07:22 UTC, publdaze commented on src/App.tsx
> +  };
저희 공부했던 공식문서에 보면 핸들러 함수에는 보통 `handle`이라는 prefix를 사용한다고 되어있어요! 저희도 동일하게 `handle` prefix를 사용하는 걸로 컨벤션 맞춰주면 어떨까요?

2023-06-23 07:32 UTC, pipisebastian commented on src/screens/GameStart.tsx
> +        disabled={parseInt(point, 10) > 1000 || parseInt(point, 10) < 10 || point === ''}
parseInt가 기본적으로 10진법으로 바꿔줘서, `parseInt(point)` 만 해도 작동될 겁니다! 그치만 10 넣는 것도 직관적으로 보여서 좋은 것 같아욥!

2023-06-23 07:33 UTC, pipisebastian commented on src/screens/GameStart.tsx
> +          setPoint(e.target.value.replace(/[^0-9]/g, ''));
정규식으로 숫자 제외한거는 ''으로 바꿔주는거 너무 좋은 생각입니다!! 알아가요!

2023-06-23 07:33 UTC, pipisebastian approved these changes

2023-06-23 07:36 UTC, wns1826 approved these changes

2023-06-23 07:39 UTC, publdaze commented on src/screens/GameStart.tsx
> +const GameStart = ({ onStart }: { onStart: any }) => {
`onStart` 타입의 경우 아무것도 반환하지 않는 함수니까
`onStart: () => void` 로 타입 지정할 수 있을 것 같아요!

props 받아오는 부분에 직접적으로 타입 지정해주는 게 지금은 props로 onStart 하나만 받아오고 있지만
props 수가 많아지면 지저분해 보일 수도 있는데 그럴 경우에는 아래처럼 interface 따로 분리하여 작성도 가능할 것 같아요 😀

```tsx
interface GameStartProps {
  onStart: () => void;
}

const GameStart = ({ onStart }: GameStartProps) => {
```

2023-06-23 07:51 UTC, KimHaejoong1 commented on src/App.tsx
> +  };
좋은 것 같아요! 반영했습니다!

2023-06-23 07:51 UTC, KimHaejoong1 commented on src/screens/GameStart.tsx
> +const GameStart = ({ onStart }: { onStart: any }) => {
반영했습니다!

2023-06-23 07:54 UTC, publdaze commented on src/screens/GameStart.tsx
> +        disabled={parseInt(point, 10) > 1000 || parseInt(point, 10) < 10 || point === ''}
저돋 parseInt가 기본적으로 10진법으로 바꿔주는 줄 알았는데 [parseInt mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt#description) 살펴보니 항상 기본값이 10인건 아닌가보더라구요 😮
기본값이 10이 아닌 경우도 mdn 문서에 적혀 있는 것 같은데 궁금하면 읽어봐도 좋을 것 같아요~!

<img width="789" alt="image" src="https://github.com/KEEPER31337/Game-Baseball/assets/78250089/7c6a87e7-298a-4a76-8513-ace438440231">

2023-06-23 08:08 UTC, publdaze commented on src/screens/GameStart.tsx
> +        className="text-2xl enabled:hover:text-pointBlue"
`enabled` 사용한 거 처음 보는데 disabled 처리가 안 되어있을 때만 스타일 적용하는 게 가능했군요..!! 배워갑니다!
혹시 disabled 상태일 때도 회색이라거나 버튼이 비활성 상태라는 게 표현되도록 추가로 처리해주는 건 어떨까요?

2023-06-23 08:14 UTC, pipisebastian commented on src/screens/GameStart.tsx
> +        disabled={parseInt(point, 10) > 1000 || parseInt(point, 10) < 10 || point === ''}
헐루~~~ 궁금해서 찾아봤는데 이렇다고 합니다!! 알아가욤!~~
![image](https://github.com/KEEPER31337/Game-Baseball/assets/81643702/985f9bd5-ad3a-4e22-a83b-e279e8bbe799)

2023-06-23 08:15 UTC, publdaze requested changes

2023-06-23 08:15 UTC, publdaze commented on src/screens/GameStart.tsx
> +      <div className="mb-10 text-2xl">batting your point...</div>
허걱 제가 피그마에 시작화면 구성할 때 오타 냈었네요..! 죄송합니다!
betting으로 수정 부탁드립니다!

2023-06-23 08:15 UTC, publdaze commented on src/screens/GameStart.tsx
> +        disabled={parseInt(point, 10) > 1000 || parseInt(point, 10) < 10 || point === ''}
버튼 유효성 검사도 처리해주다니! 짱짱입니다! 👍

숫자 범위 확장성 있게 최소 숫자, 최대 숫자 변수로 상단에 빼주면 좋을 것 같아요! (아직 백엔드에서 API 구현은 안된 걸로 아는데 베팅 포인트 범위도 API에서 받아와서 처리해주면 좋을 것 같아요!)

const MIN_BETTING_POINT = 10;
const MAX_BETTING_POINT = 1000;

요런 식으로 변수 선언해두고 가져오면 어떨까합니다!

2023-06-23 08:42 UTC, KimHaejoong1 commented on src/screens/GameStart.tsx
> +        className="text-2xl enabled:hover:text-pointBlue"
기본 색깔이 흰색이어서 disabled 일때 회색으로 수정했습니다!

2023-06-23 08:43 UTC, KimHaejoong1 commented on src/screens/GameStart.tsx
> +      <div className="mb-10 text-2xl">batting your point...</div>
오타 수정했습니다!

2023-06-23 08:43 UTC, KimHaejoong1 commented on src/screens/GameStart.tsx
> +        disabled={parseInt(point, 10) > 1000 || parseInt(point, 10) < 10 || point === ''}
반영했습니다!

2023-06-23 15:14 UTC, publdaze approved these changes
수고하셨습니다! 첫 PR인데 너무 잘해주셨네요! 굿굿👍👍

2023-06-24 07:01 UTC, publdaze requested changes

2023-06-24 07:01 UTC, publdaze commented on src/screens/GameStart.tsx
> +  const [point, setPoint] = useState<string>('');
- #30 이 PR 리뷰하다가 `point`라는 변수명이 겹쳐서 추가로 리뷰 달아봅니다!

포인트 변수명 관련해서 포인트라는 네이밍을 가질 수 있는 경우가
- 회원이 보유한 포인트
- 베팅할 포인트
- 게임으로 획득 가능한 포인트

등 다양한 경우가 있기 때문에 어떤 걸 지칭하는 지 좀 더 변수명을 명확히 해주면 나중에 유지보수하거나 코드를 읽는 입장에서 좀 더 이해해기 쉬울 것 같아요!

여기서는 베팅하는 포인트니까 `point` -> `bettingPoint`로 어떨까합니다!

2023-07-16 09:03 UTC, KimHaejoong1 commented on src/screens/GameStart.tsx
> +  const [point, setPoint] = useState<string>('');
`bettingPoint` 로 수정했습니다!

2023-07-16 09:15 UTC, publdaze requested changes

2023-07-16 09:15 UTC, publdaze commented on src/screens/GameStart.tsx
> +
set함수도 `setPoint` -> `setBettingPoint`로 변경된 state 변수명 같이 바꿔주면 좋을 것 같아요!

2023-07-16 09:21 UTC, KimHaejoong1 commented on src/screens/GameStart.tsx
> +
set함수도 수정했습니다!

2023-07-16 09:33 UTC, publdaze approved these changes
👍👍

2023-07-29 05:20 UTC, merged