feat : 카운트다운 progress bar 구현
KEEPER31337/Game-Baseball pull request #28
Opened 2023-06-04 17:15 UTC by pipisebastian

## 연관 이슈

- close #4 
- 해당 이슈 설명은 추후에 변경하겠습니다..!

## 작업 요약

- 카운트다운 progress bar 구현
- js의 setInterval, clearInterval 사용했습니다. 해당 [블로그](https://velog.io/@pipi/%EB%A6%AC%EC%95%A1%ED%8A%B8-%EC%B9%B4%EC%9A%B4%ED%8A%B8%EB%8B%A4%EC%9A%B4-%EA%B5%AC%ED%98%84)에 정리했는데, 궁금하신 분들은 읽어봐주세요!
- 주요 로직을 제 생각대로 와다다 짠거라,, 많은 피드백 부탁드립니다!! 

## 작업 상세 설명

- **주요 로직** 
- 게임을 실행하는지, 안하는지를 알려주는 props로 flag를 받아옵니다.
- 처음 게임을 start했을때 flag를 true로 바꿔주고, 카운트 다운이 실행됩니다.
- 중간에 입력을 다 하고, 야구공 버튼을 누르면, flag를 false로 바꿔주고 카운트 다운이 멈춥니다.
- 혹은 30초가 다 지났을 경우에도  flag를 false로 바꿔주고 카운트 다운이 멈춥니다.
- 결과를 확인하고 다시 게임을 시작하면 flag를 true로 바꿔줍니다.
- 해당 flag변수는 GamePlay컴포넌트에서 선언해야 합니다!

- 코드에 대해서는 댓글에서 자세하게 설명하겠습니다!

## 리뷰 요구사항

- 5분
![image](https://github.com/KEEPER31337/Game-Baseball/assets/81643702/114133a9-9196-469a-b325-a16d326feb51)
해당 flag를 true, false로 체크박스 눌러서 바꾸시면 테스트할 수 있습니다!

- Preview 이미지
![image](https://github.com/KEEPER31337/Game-Baseball/assets/81643702/c0b3d20f-ec51-4624-b9f0-d28f23839fcb)

2023-06-04 17:17 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +  const countPercentage = (count / maxCount) * 100;
maxCount는 카운트다운 시간이며, 중간에 쓰일 일이 많기에 변수로 넣어놨습니다.
countPercentage는 0~30초 시간을, 추후에 디자인에서는 0~100% width로 표현해줄 것이기 때문에, 0~30 -> 0~100으로 변환하는 식입니다!

2023-06-04 17:19 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +    } else handleStop();
flag가 바뀌었을 경우, flag가 true이면 게임을 다시 시작하는 것이므로, count를 30초로 다시 맞추고 카운트다운(setInterval)을 시작합니다.
flag가 false이면 카운트다운(clearInterval)을 멈춥니다.

2023-06-04 17:21 UTC, pipisebastian commented
핫핫 기능과 ui를 따로 안했네요!! 다음엔 분리하겠씁니다..

2023-06-05 01:29 UTC, jasper200207 approved these changes

2023-06-23 00:29 UTC, wns1826 approved these changes

2023-06-23 05:39 UTC, KimHaejoong1 approved these changes

2023-06-23 15:35 UTC, publdaze reviewed
리뷰 한차례 끊어서 해보겠습니다! 내일 마저달아 볼게요!!

2023-06-23 15:35 UTC, publdaze commented on src/components/CountdownBar.tsx
> +    <div className="App">
여기 App이라는 클래스가 어떤 역할으로 들어간건지 궁금합니다!
App 컴포넌트에서 App에 대한 클래스 제공하기 위해 보통 App 클래스 사용되는 것 같아서 (저희 프로젝트에서는 따로 의미를 두고 넣은 건 아니고 cra에서 제공해주는 App 컴포넌트 그대로 남겨둔거긴 하지만요 ㅎㅎ) 따로 의도된게 있는 지 궁금합니다!

2023-06-23 15:35 UTC, publdaze commented on src/components/CountdownBar.tsx
> +          className="h-6 bg-pointBlue transition-all duration-1000 ease-linear"
width만 tailwind가 아닌 별도의 인라인스타일로 적용해준 이유가 있을까요?~?

2023-06-23 15:35 UTC, publdaze commented on src/components/CountdownBar.tsx
> +        setCount((cnt) => cnt - 1);
이전값 반영해서 state 업데이트 하는거 굿굿입니다!

2023-06-28 00:23 UTC, publdaze requested changes
타이머 어렵네요..! 블로그 글 정리 굿굿입니다!

2023-06-28 00:23 UTC, publdaze commented on src/components/CountdownBar.tsx
> +  flag: boolean;
`flag`의 경우 뭔가 boolean값으로 제어한다는 변수명이라는 건 알 수 있을 것 같은데
직접적으로 어떤 상태를 나타내는 지 와닿지 않는 것 같아요!
여기서는 turn이 시작됐는 지 여부를 나타내는 게 맞을까요?
맞다면 `is` prefix로도 boolean값을 표현할 수 있으니 `isTurnStart` 같은 식으로 변수명을 좀 더 명확하게 써보면 어떨까요?

2023-06-28 00:23 UTC, publdaze commented on src/components/CountdownBar.tsx
> +  };
저희가 이벤트 핸들러에 주로 `handle`이라는 prefix를 사용하기 때문에 이 코드를 처음 보는 사람이 해당 함수를 딱 접했을 때 이벤트 핸들라고 생각하게 될 수도 있을 것 같아서 네이밍에 `handle`은 제거하면 어떨까요?
그리고 start, stop되는 대상이 무엇인지도 변수명에 포함해주면 좀 더 해당 변수명이 의미하는 걸 알아보기 좋을 것 같습니다!

2023-07-16 05:27 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +    <div className="App">
호호.. 복붙했습니다.. 수정하겠습니다!

2023-07-16 06:09 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +          className="h-6 bg-pointBlue transition-all duration-1000 ease-linear"
아 tailwind에서 width에 vw나 % 넣어도 적용이 안돼더라구요! 혹시 방법 있을까요??
사용한 코드는 이겁니다 
```
   <div className={`w-[${countPercentage}%] h-6 bg-pointBlue transition-all duration-1000 ease-linear`} />
   <div className={`w-[${countPercentage}vw] h-6 bg-pointBlue transition-all duration-1000 ease-linear`} />
```

2023-07-16 06:13 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +  flag: boolean;
조아요~ 수정햇습니당

2023-07-16 06:17 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +  };
좋습니다! countdown으로 prefix바꿨는데 괜찮을까욥!

2023-07-16 06:20 UTC, publdaze commented on src/components/CountdownBar.tsx
> +  };
카운트 다운을 처리하는 함수라는 것도 한 눈에 알 수 있어서 좋은 것 같습니다! 👍

2023-07-16 06:42 UTC, publdaze commented on src/components/CountdownBar.tsx
> +          className="h-6 bg-pointBlue transition-all duration-1000 ease-linear"
다이나믹 class 적용할 때 [공식문서](https://tailwindcss.com/docs/content-configuration#dynamic-class-names)에서 fullname으로 처리해야 한다고 되어있는 것 같은데 임의값만 변수로 두는 방식이 아닌 크래스 자체를 적용하면 될 것 같습니다.

2023-07-16 06:45 UTC, publdaze requested changes

2023-07-16 06:45 UTC, publdaze commented on src/components/CountdownBar.tsx
> +const CountdownBar = ({ isTurnStart }: CountdownProps) => {
인터페이스 네이밍에 Bar 넣어줘야 할 것 같아요! 😄

2023-07-16 07:55 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +          className="h-6 bg-pointBlue transition-all duration-1000 ease-linear"
움냐링.. 잘 안됩니다!! 도와주세요!!! 찾아보면 case별로 분리한 것만 보이고(color, size), 변수 자체를 넘겨줘서 적용하는 건 못찾겠습니다!!!ㅜㅜ
```
const colorVariants = ` h-6 bg-pointBlue transition-all duration-1000 ease-linear`;

  return (
    <div>
      <div className="h-6 w-[350px] bg-pointGray">
        <div className={`${colorVariants}`} />
      </div>
    </div>
  );
```
여기서 아무것도 못했씁니다!

2023-07-16 08:16 UTC, publdaze commented on src/components/CountdownBar.tsx
> +          className="h-6 bg-pointBlue transition-all duration-1000 ease-linear"
일단 제가 처음 의도했던 건
```tsx
<div className={`w-[${countPercentage}%] h-6 bg-pointBlue transition-all duration-1000 ease-linear`} />
```
->
```tsx
<div className={`${countPercentageWidth} h-6 bg-pointBlue transition-all duration-1000 ease-linear`} />
```

이런 형식이었긴 한데 직접 해보니까 이렇게 전체를 변수로 둬도 값이 변함에 따라 컴포넌트 렌더링을 다시 되는 것 같아보이는데 화면에 변화된 css UI는 반영이 안 되는 것 같네요!

일단 inline 스타일로 가는 걸로 합시다! 따로 원인이나 해결법 찾으면 공유 부탁드려요! 😄

2023-07-16 08:24 UTC, pipisebastian commented on src/components/CountdownBar.tsx
> +          className="h-6 bg-pointBlue transition-all duration-1000 ease-linear"
넵넵!! 감사합니당!!!

2023-07-16 08:42 UTC, publdaze approved these changes
👍👍

2023-07-16 08:43 UTC, merged