Feature/모든 회차 구성 #6
KEEPER31337/Game-Baseball pull request #29
Opened 2023-06-05 02:47 UTC by jasper200207

## 연관 이슈

- #6

## 작업 요약

- 게임 결과를 props로 받아 모든 회차를 보여주는 컴포넌트

## 작업 상세 설명

- props로 results, round를 받습니다
   results : Array<ResultDto | null> (게임결과 리스트)
   round : number (최대 라운드 개수)

- ResultDto가 변경되었습니다
  ball : number
  strike : number
  guessNumber : 숫자 4자리인 string (추가)

- 받은 props를 바탕으로 renderList를 만들고, map으로 render 합니다
   results 의 길이만큼 'Finished'를 추가
   만약 round 수가 남으면 'Playing' 1개 추가
   그래도 남은 수만큼 'Ready' 추가

## 리뷰 요구사항

- 5분
- guessNumber를 그냥 string으로 하지않고 더 엄격하게 정의했는데 그냥 string과 비교해서 뭐가 좋을지 의견 부탁드립니다.
- key값을 정할만한 고유값이 없어 index로 정했는데 좋은 키값이 있을지 의견 부탁드립니다.

- Preview 이미지
<img width="341" alt="스크린샷 2023-06-05 오전 11 21 02" src="https://github.com/KEEPER31337/Game-Baseball/assets/51306225/da9d6dfc-2561-4337-a44e-92e2a23c2fa4">

2023-06-05 02:48 UTC, jasper200207 commented on src/components/TurnInfoBoard.tsx
> +import TurnInfoCard, { ResultDto } from './TurnInfoCard';
일단 지금은 임시로 TurnInfoCard에 있는 ResultDto를 받아왔습니다.
API 작업 이후에는 API에서 Dto 받아올 예정입니다.

2023-06-05 02:51 UTC, jasper200207 commented on src/components/TurnInfoBoard.tsx
> +        /* eslint-disable react/no-array-index-key */
eslint가 index를 키값으로 쓰지못하도록 막아서 비활성화 했습니다. 혹시 좋은 키값 있으면 추천부탁드립니다.

2023-06-05 02:51 UTC, jasper200207 commented on src/components/TurnInfoBoard.tsx
> +  if (round > results.length + 1) renderList.push(...new Array(round - results.length - 1).fill('Ready'));
반복문 대신에 새로 리스트를 만들고 전개연산자로 넣었는데 반복문이 좋을까요?

2023-06-05 02:52 UTC, jasper200207 commented on src/components/TurnInfoCard.tsx
> +type digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9';
digit을 0~9까지 1자리수로 정의하고 guessNumber를 ``를 사용해서 엄밀하게 만든 타입입니다.

2023-06-05 02:53 UTC, jasper200207 commented on src/components/TurnInfoBoard.tsx
> +        <TurnInfoCard key={index} index={index + 1} result={results?.[index]} status={status} />
eslint가 index를 키값으로 쓰지못하도록 막아서 비활성화 했습니다. 혹시 좋은 키값 있으면 추천부탁드립니다.

2023-06-05 02:53 UTC, jasper200207 commented on src/components/TurnInfoCard.tsx
> +  guessNumber: `${digit}${digit}${digit}${digit}`;
digit을 0~9까지 1자리수로 정의하고 guessNumber를 ``를 사용해서 엄밀하게 만든 타입입니다.

2023-06-23 05:42 UTC, KimHaejoong1 approved these changes

2023-06-23 08:04 UTC, pipisebastian commented on src/components/TurnInfoBoard.tsx
> +  if (round > results.length + 1) renderList.push(...new Array(round - results.length - 1).fill('Ready'));
저는 전개연산자가 좋습니다!

2023-06-23 08:04 UTC, pipisebastian approved these changes

2023-06-23 08:25 UTC, wns1826 approved these changes

2023-06-23 08:25 UTC, publdaze commented on src/components/TurnInfoBoard.tsx
> +  results: Array<ResultDto | null>;
오홍 매번 (타입)[] 이런식으로 배열 타입 지정했어서 Array<타입>으로 배열 타입 지정할 수 있다는 걸 잊고 있었는데 다시 복습해갑니다~!

차이점이 혹시 있을 지 궁금해서 찾아봤는데 큰 차이는 없는 것 같고 튜플로 사용하려고 할 때 고정된 길이로 처리가 되는 지 여부 정도 차이가 있는 것 같아 같아보이네용 🧐
<img width="847" alt="image" src="https://github.com/KEEPER31337/Game-Baseball/assets/78250089/19665208-178a-45c8-a45d-e4b503631de3">
([참고](https://stackoverflow.com/questions/36842158/arraytype-vs-type-in-typescript))

2023-06-23 08:31 UTC, publdaze commented on src/components/TurnInfoBoard.tsx
> +        <TurnInfoCard key={index} index={index + 1} result={results?.[index]} status={status} />
`renderList`에 key값으로 받아올 `id`속성과 `status`속성으로 구성된 객체리스트로 구성해보는 건..? 어떨까요? 🧐

2023-06-23 12:57 UTC, publdaze commented on src/components/TurnInfoCard.tsx
> +  guessNumber: `${digit}${digit}${digit}${digit}`;
오호 확실히 4자리수에 들어갈 수 있는 숫자들을 지정해줘서 엄격하게 타입 체크할 수 있겠네요!! 👍👍

저희가 4자리수를 사용하기로 정했어서 크게 고려할 필요는 없을 것 같지만, 만약 규칙을 변경하여 자리수가 늘어날 경우를 가정하여 확장성있게도 작성할 수 있는 방법이 있을 지도 궁금하네요 🤔

(그냥 string으로 적용하는 게 좋을 지 이렇게 엄격하게 적용하는 게 좋을 지는 판단 기준을 어떻게 두면 좋을지 모르겠어서 저도 잘 모르겠어요..ㅎㅎ 더 실력을 쌓아서 이런 것도 척척 판단할 수 있도록 노력해보겠습니닷...!!)

2023-06-24 06:32 UTC, publdaze requested changes

2023-06-24 06:32 UTC, publdaze commented on src/components/TurnInfoBoard.tsx
> +  if (round > results.length + 1) renderList.push(...new Array(round - results.length - 1).fill('Ready'));
제가 지식이 얕아서 괜한 걱정일 수도 있지만, (동일한 렌더링 내에 수행되는 작업인 것 같아 괜찮을 수도 있지만) 아무래도 배열을 변경하는 것이다 보니 순수성 보장에 대한 부분이 조금 우려가 되고, push되는 작업이 나눠서?처리되다 보니 비동기 관련해서도 사이드이펙트가 발생할 가능성 있지 않을까하는 부분도 염려가 되어서 처음 배열을 생성할 때 해당 상태 정보를 한 번에 처리하는 건 어떤지 제안드립니다!

```suggestion
  const renderList = Array.from({ length: round }, (v, i) => {
    if (i === results.length) return 'Playing';
    if (i > results.length) return 'Ready';
    return 'Finished';
  });
```
`from` 함수 사용한 것은 제가 지금 생각나는 방식이 이것 밖에 없어서 `from` 사용한 거고 더 좋은 방식이 있다면 다른 방식으로 하시면 될 것 같습니다! 초첨은 `round`수로 고정된 길이의 array로 생성 시에 상태를 부여하는 방식을 사용한다는 걸로 봐주면 될 것 같아요!

2023-06-24 06:42 UTC, publdaze commented
[refactor : GamePlay.tsx 변경사항 제거](https://github.com/KEEPER31337/Game-Baseball/pull/29/commits/7e7f12d4292a6a7f7174ec1928763cb452ea3933)

해당 커밋에서 충돌 방지로 변경사항 제거해주셨는데
이 변경사항이 없을 때 프로젝트 실행하면 에러가 발생해서 develop 머지됐을 때 develop기반으로 브랜치 따서 작업하면 다들 에러 따로 처리해줘야해서 불편 사항이 조금 있을 것 같아요!

만약 충돌 나면 처리해서 올리는 걸로 하고 GamePlay.tsx 변경사항도 일단 포함시켜 주는 건 어떨까요?

2023-06-30 12:54 UTC, jasper200207 commented on src/components/TurnInfoBoard.tsx
> +  if (round > results.length + 1) renderList.push(...new Array(round - results.length - 1).fill('Ready'));
from에 함수가 들어가는걸 몰랐네요... 안그래도 한번에 하고 싶었는데 반영하겠습니다!

2023-06-30 13:00 UTC, jasper200207 commented on src/components/TurnInfoBoard.tsx
> +  results: Array<ResultDto | null>;
좋은 정보 감사합니다!

2023-07-01 05:10 UTC, publdaze approved these changes
굿굿~~

2023-07-01 09:42 UTC, merged