Feature/획득 가능 포인트 섹션 구현 #3
KEEPER31337/Game-Baseball pull request #30
Opened 2023-06-23 06:34 UTC by wns1826

## 연관 이슈

- #3 

## 작업 요약

- 획득 가능한 포인트 표시

## 작업 상세 설명

- 획득 가능한 포인트를 props로 받아 표시합니다

## 리뷰 요구사항

- 리뷰 예상 시간: 1분

- Preview 이미지
![image](https://github.com/KEEPER31337/Game-Baseball/assets/14329410/cc92ab1e-15e2-4a43-b259-d356d88ac9b5)

2023-06-23 07:22 UTC, KimHaejoong1 approved these changes

2023-06-23 07:30 UTC, jasper200207 approved these changes

2023-06-23 08:17 UTC, pipisebastian approved these changes

2023-06-24 07:07 UTC, publdaze requested changes

2023-06-24 07:07 UTC, publdaze commented on src/components/PointInfo.tsx
> +  point: number;
- #27 이 PR에서도 `point`라는 변수명을 사용하고 있더라구요!

포인트 변수명 관련해서 포인트라는 네이밍을 가질 수 있는 경우가

- 회원이 보유한 포인트
- 베팅할 포인트
- 게임으로 획득 가능한 포인트

등 다양한 경우가 있기 때문에 어떤 걸 지칭하는 지 좀 더 변수명을 명확히 해주면 나중에 유지보수하거나 코드를 읽는 입장에서 좀 더 이해해기 쉬울 것 같아요!

여기서는 획득 가능한 포인트니까 `point` -> `earnablePoint`로 어떨까합니다!

2023-07-16 05:06 UTC, publdaze approved these changes
👍👍

2023-07-17 10:06 UTC, merged