Feature/숫자 입력 컴포넌트 구현 #7
KEEPER31337/Game-Baseball pull request #31
Opened 2023-06-23 06:46 UTC by wns1826

## 연관 이슈

- #7 

## 작업 요약

- 4자리 숫자를 입력 받는 컴포넌트 구현

## 작업 상세 설명

- [otp-input-react](https://npm.io/package/otp-input-react) 패키지를 사용해 구현하였습니다.

## 리뷰 요구사항
- 리뷰 예상시간: 5분
- 패키지 신규 설치로 package.json이 수정되었으니 확인 부탁드립니다.
- Preview 이미지
![image](https://github.com/KEEPER31337/Game-Baseball/assets/14329410/79c316a4-8187-47b4-89df-1935f0e65bea)

2023-06-23 07:28 UTC, jasper200207 approved these changes
수고하셨습니다

2023-06-23 07:28 UTC, KimHaejoong1 approved these changes

2023-06-23 08:24 UTC, pipisebastian approved these changes

2023-06-23 08:29 UTC, pipisebastian reviewed
혹시 해당 링크 참고하셔서 만들어보는건 어떨까욥??
지금 키퍼 리뉴얼에서, 연후님이 맡고 계신 파트인데, 기능적으로 똑같아 보여서요!

2023-07-24 01:31 UTC, wns1826 commented
패키지 관련 내용은 아래 노션에 작성해두었습니다!

https://fuchsia-tabletop-6fc.notion.site/b4cb396a46cb494e95cf3188c8593927

2023-07-29 05:32 UTC, jasper200207 approved these changes

2023-07-29 05:36 UTC, publdaze requested changes

2023-07-29 05:36 UTC, publdaze commented on src/components/NumberInput.tsx
> +  const [number, setNumber] = useState('');
좀 더 명확하게 `guessNumber`로 네이밍 하면 어떨까요? api request key값과도 동일해서 request 보낼때 편할 것 같아요!

2023-07-29 05:36 UTC, publdaze commented on src/components/NumberInput.tsx
> +  };
우왕! res로 받아오는 값이 각자리 값 붙여서 바로 제공해주는 군요! 👍

2023-07-29 06:08 UTC, publdaze approved these changes
👍👍

2023-07-29 06:11 UTC, KimHaejoong1 approved these changes

2023-07-29 06:13 UTC, pipisebastian commented on src/screens/GamePlay.tsx
> +  const [guessNumber, setGuessNumber] = useState('');
혹시 이거는 type <string> 안넣은 이유가 있을까욥??

2023-07-29 06:15 UTC, merged