Feature/api 요청 코드 작성 #20
KEEPER31337/Game-Baseball pull request #32
Opened 2023-06-23 07:26 UTC by jasper200207

## 연관 이슈

- #20

## 작업 요약

- UseQuery로 작성한 API 코드 입니다

## 작업 상세 설명

DTO
- GuessNumber : 추측숫자, 4자리숫자 고정으로 정의했습니다
- ResultInfo : 한번 추측에 대한 결과 입니다.
- GameResultInfo : 전체 게임에 대한 결과 입니다.
API
- [useGetIsAlreadyPlayed](http://dev.keeper.or.kr:81/docs/game/baseball.html#_플레이_했는지_확인하기)
- [useGameStart](http://dev.keeper.or.kr:81/docs/game/baseball.html#_야구_게임_start)
- [useGetGuess](http://dev.keeper.or.kr:81/docs/game/baseball.html#_야구_게임_guess)
- [useGetResult](http://dev.keeper.or.kr:81/docs/game/baseball.html#_야구_게임_결과_가져오기)
## 리뷰 요구사항

- 8분
- useQuery로 api 코드 작성은 처음이라 깐깐하게 리뷰 부탁드립니다

2023-06-23 07:52 UTC, KimHaejoong1 approved these changes

2023-06-23 08:25 UTC, pipisebastian approved these changes

2023-06-23 15:50 UTC, publdaze requested changes

2023-06-23 15:50 UTC, publdaze commented on src/api/baseballApi.ts
> +  return useQuery<GameResultInfo>(quearyKeys.guess, fetcher);
POST의 경우는 useQuery가 아닌 useMutate? useMutation? 잘 기억이 안 나는데 둘중 하나로 작성해야하는 걸로 알고 있습니다! 내일 문서 한 번 찾아보고 추가 코멘트 남겨두겠습니다!

2023-06-24 07:11 UTC, publdaze commented
오오 PR 작업 상세 설명에 각 API 문서 링크도 다 달아주셨었네요!! 👍👍 감사합니다!

2023-06-24 07:30 UTC, publdaze commented on src/api/baseballApi.ts
> +  return useQuery<GameResultInfo>(quearyKeys.guess, fetcher);
서버의 데이터를 수정하는 경우 `useMutation` 사용하면 될 것 같아요! 여기서도 `useMutation` 하면 될 것 같아요!

저는 react-query 사용할 때 [이 글](https://tech.kakaopay.com/post/react-query-1/) 많이 참고했었는데 궁금하다면 한 번 살펴봐도 좋을 것 같아요!

2023-06-24 07:35 UTC, publdaze reviewed
`모든 회차 구성` 커밋도 포함되어있어서 pull 받아서 진행한 줄 알았는데 pull 받은 내역은 없는 것 같아서 브랜치 시작 지점이 `모든 회차 구성` 브랜치에서 시작된 게 아닐까 싶네요!
다음 작업할 브랜치 새로 팔 때 브랜치 시작 지점 `main`으로 되어 있는 지 한 번 확인해봐주면 좋을 것 같아요!

2023-06-24 07:48 UTC, publdaze reviewed
API 작동 되는 지 테스트는 아직 안 된 상태인거죠?~?

해당 PR 변경사항에는 baseURL 설정한 부분이 안 보이는데 서버 url 포함 안 되어 있으면 아마 작동 안 될 것 같아보이는데 확인 부탁드립니다!
(앗 이제 봤는데 `/api`로 서버주소 대체해서 일단 임시로 넣어둔 걸까요? 그럼 아래 방식으로 처리하면 어떨 지 제안 드립니다!)

제가 리뉴얼2 프로젝트할 때는 `env` 파일에 서버 주소 넣어두고 `index.tsx` 파일에 아래 코드 추가하여 axios baseURL 추가해서 불러오는 부분에서는 baseURL 제외한 경로만 넣어도 동작할 수 있도록 처리해줬었습니다!

```tsx
axios.defaults.baseURL = process.env.REACT_APP_API_URL;
```

2023-06-24 07:54 UTC, publdaze reviewed
https://github.com/KEEPER31337/Homepage-Front-R2/pull/386
이 PR은 제가 리뉴얼2 프로젝트에서 회원가입 API 불러오는 코드 작성해본건데 작동 되는 것도 테스트 완료된 코드입니다! 
get, post 두 종류 다 사용했어서 혹시 필요하다면 참고해주시고 실례가 안 된다면 리뷰도 부탁드려도 될까요? ㅎㅎ (도균님 리뷰어 아니었긴 한데 추가로 달아두었습니다! 😆)

2023-06-30 13:12 UTC, jasper200207 commented
> `모든 회차 구성` 커밋도 포함되어있어서 pull 받아서 진행한 줄 알았는데 pull 받은 내역은 없는 것 같아서 브랜치 시작 지점이 `모든 회차 구성` 브랜치에서 시작된 게 아닐까 싶네요! 다음 작업할 브랜치 새로 팔 때 브랜치 시작 지점 `main`으로 되어 있는 지 한 번 확인해봐주면 좋을 것 같아요!

방금 확인했는데 실수로 브랜치 시작점을 잘못잡았네요....

2023-07-16 05:34 UTC, publdaze approved these changes
👍👍 아래 리뷰 한 번 괜찮다 싶으면 반영해주시고, 나머지 더 리뷰할 건 없는 것 같아서 approve 해두겠습니다! 수고하셨어요!

2023-07-16 05:34 UTC, publdaze commented on src/api/baseballApi.ts
사용하는 쪽에서도 query인지 mutation인지 알 수 있으면 좋을 것 같은데 subfix로 달아주면 어떨까요?~?

2023-07-16 06:44 UTC, jasper200207 commented on src/api/baseballApi.ts
> 사용하는 쪽에서도 query인지 mutation인지 알 수 있으면 좋을 것 같은데 subfix로 달아주면 어떨까요?~?

좋은거 같습니다! 반영하겠습니다

2023-07-16 08:03 UTC, pipisebastian approved these changes

2023-07-16 08:04 UTC, wns1826 approved these changes

2023-07-17 07:57 UTC, merged